
baseurl: "/misc" 

title: Arizona Phonological Imaging Lab
email: trevortds@email.arizona.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the documentation page for the Arizona Phonological Imaging lab. 
baseurl: "/misc" 
url: "http://arizona-phonological-imaging-lab.github.io/misc/" # the base hostname & protocol for your site
github_username:  trevortds

category-list: [autotres, matlabversion, webapp]
# Build settings
markdown: kramdown
